# -*- coding: UTF-8 -*-
import os.path

ROOTDIR = os.path.join(os.path.dirname( \
    os.path.realpath(__file__)), '..')
TMPLDIR = os.path.join(os.path.dirname( \
    os.path.realpath(__file__)), '..', 'template')
OUTDIR = os.path.join(os.path.dirname( \
    os.path.realpath(__file__)), '..', 'html')
SYMDIR = os.path.join(ROOTDIR, 'data/symbol')
HIST_DIR = {
    'stock': os.path.join(ROOTDIR, 'data/history/stock'),
    'index': os.path.join(ROOTDIR, 'data/history/index'),
}
FINANCE_DIR = {
    'stock': os.path.join(ROOTDIR, 'data/finance/stock')
}
BASIC_DIR = os.path.join(ROOTDIR, 'data/basics')

REAL_DIR = {
    'stock': os.path.join(ROOTDIR, 'data/realtime/stock'),
    'daily': os.path.join(ROOTDIR, 'data/realtime/daily'),
}

TICK_DIR = {
    'stock': os.path.join(ROOTDIR, 'data/tick/stock'),
    'daily': os.path.join(ROOTDIR, 'data/tick/daily'),
}

KAIPAN_DIR = {
    'stock': os.path.join(ROOTDIR, 'data/kaipan/stock'),
    'daily': os.path.join(ROOTDIR, 'data/kaipan/daily'),
}

SYM = {
    'all': os.path.join(SYMDIR, 'symbols.all'),
    'id':  os.path.join(SYMDIR, 'symbols.id'),
    'wbond': os.path.join(SYMDIR, 'symbols.wbond')
}

IPO_DIR = os.path.join(ROOTDIR, 'data/ipo')
IPOLIST = os.path.join(IPO_DIR, 'list')

INDEX = {
    'sh': 'sh000001',
    'sz': 'sz399001',
    'cy': 'sz399006',
}

ARCHIVED_YEARS = ["16","15","14","13","12","11","10","09","08","07","06"]
DBFILE = os.path.join(ROOTDIR, 'cnstock.db')
LOGCONF = os.path.join(ROOTDIR, 'conf', 'logging.conf')

LRB_CH2EN = {
    "营业总收入(万元)": "yyzsr",
    "营业收入(万元)": "yysr",
    "利息收入(万元)": "lxsr",
    "已赚保费(万元)": "yzbf",
    "手续费及佣金收入(万元)": "sxfjyjsr",
    "房地产销售收入(万元)": "fdcxssr",
    "其他业务收入(万元)": "qtywsr",
    "营业总成本(万元)": "yyzcb",
    "营业成本(万元)": "yycb",
    "利息支出(万元)": "lxzc",
    "手续费及佣金支出(万元)": "sxfjyjzc",
    "房地产销售成本(万元)": "fdcxscb",
    "研发费用(万元)": "yffy",
    "退保金(万元)": "tbj",
    "赔付支出净额(万元)": "pfzcje",
    "提取保险合同准备金净额(万元)": "tqbxhtzbjje",
    "保单红利支出(万元)": "bdhlzc",
    "分保费用(万元)": "fbfy",
    "其他业务成本(万元)": "qtywcb",
    "营业税金及附加(万元)": "yysjjfj",
    "销售费用(万元)": "xsfy",
    "管理费用(万元)": "glfy",
    "财务费用(万元)": "cwfy",
    "资产减值损失(万元)": "zcjzss",
    "公允价值变动收益(万元)": "gyjzbdsy",
    "投资收益(万元)": "tzsy",
    "对联营企业和合营企业的投资收益(万元)": "dlyqyhhyqydtzsy",
    "汇兑收益(万元)": "hdsy",
    "期货损益(万元)": "qhsy",
    "托管收益(万元)": "tgsy",
    "补贴收入(万元)": "btsr",
    "其他业务利润(万元)": "qtywlr",
    "营业利润(万元)": "yylr",
    "营业外收入(万元)": "yywsr",
    "营业外支出(万元)": "yywzc",
    "非流动资产处置损失(万元)": "fldzcczss",
    "利润总额(万元)": "lrze",
    "所得税费用(万元)": "sdsfy",
    "未确认投资损失(万元)": "wqrtzss",
    "净利润(万元)": "jlr",
    "归属于母公司所有者的净利润(万元)": "gsymgssyzdjlr",
    "被合并方在合并前实现净利润(万元)": "bhtfzhbqsxjlr",
    "少数股东损益(万元)": "ssgds",
    "基本每股收益": "jbmgsy",
    "稀释每股收益": "xsmgsy",
}

ZCFZB_CH2EN = {
    "货币资金(万元)": "hbzj",
    "结算备付金(万元)": "jsbfj",
    "拆出资金(万元)": "cczj",
    "交易性金融资产(万元)": "jyxjrzc",
    "衍生金融资产(万元)": "ysjrzc",
    "应收票据(万元)": "yspj",
    "应收账款(万元)": "yiszk",
    "预付款项(万元)": "yfkx",
    "应收保费(万元)": "ysbf",
    "应收分保账款(万元)": "ysfbzk",
    "应收分保合同准备金(万元)": "ysfbhtzbj",
    "应收利息(万元)": "yslx",
    "应收股利(万元)": "ysgl",
    "其他应收款(万元)": "qtysk",
    "应收出口退税(万元)": "ysckts",
    "应收补贴款(万元)": "ysbtk",
    "应收保证金(万元)": "ysbzj",
    "内部应收款(万元)": "nbysk",
    "买入返售金融资产(万元)": "mrfsjrzc",
    "存货(万元)": "ch",
    "待摊费用(万元)": "dtfy",
    "待处理流动资产损益(万元)": "dclldzcsy",
    "一年内到期的非流动资产(万元)": "ynndqdfldzc",
    "其他流动资产(万元)": "qtldzc",
    "流动资产合计(万元)": "ldzchj",
    "发放贷款及垫款(万元)": "ffdkjdk",
    "可供出售金融资产(万元)": "kgcsjrzc",
    "持有至到期投资(万元)": "cyzdqtz",
    "长期应收款(万元)": "cqysk",
    "长期股权投资(万元)": "cqgqtz",
    "其他长期投资(万元)": "qtcqtz",
    "投资性房地产(万元)": "tzxfdc",
    "固定资产原值(万元)": "gdzcyz",
    "累计折旧(万元)": "ljzj",
    "固定资产净值(万元)": "gdzcjz",
    "固定资产减值准备(万元)": "gdzcjzzb",
    "固定资产(万元)": "gdzc",
    "在建工程(万元)": "zjgc",
    "工程物资(万元)": "gcwz",
    "固定资产清理(万元)": "gdzcql",
    "生产性生物资产(万元)": "scxswzc",
    "公益性生物资产(万元)": "gyxswzc",
    "油气资产(万元)": "yqzc",
    "无形资产(万元)": "wxzc",
    "开发支出(万元)": "kfzc",
    "商誉(万元)": "sy",
    "长期待摊费用(万元)": "cqdtfy",
    "股权分置流通权(万元)": "gqfzltq",
    "递延所得税资产(万元)": "ydsdszc",
    "其他非流动资产(万元)": "qtfldzc",
    "非流动资产合计(万元)": "fldzchj",
    "资产总计(万元)": "zczj",
    "短期借款(万元)": "dqjk",
    "向中央银行借款(万元)": "xzyyhjk",
    "吸收存款及同业存放(万元)": "xsckjtycf",
    "拆入资金(万元)": "crzj",
    "交易性金融负债(万元)": "jyxjrfz",
    "衍生金融负债(万元)": "ysjrfz",
    "应付票据(万元)": "yfpj",
    "应付账款(万元)": "yfzk",
    "预收账款(万元)": "yuszk",
    "卖出回购金融资产款(万元)": "mchgjrzck",
    "应付手续费及佣金(万元)": "yfsxfjyj",
    "应付职工薪酬(万元)": "yfzgxc",
    "应交税费(万元)": "yjsf",
    "应付利息(万元)": "yflx",
    "应付股利(万元)": "yfgl",
    "其他应交款(万元)": "qtyjk",
    "应付保证金(万元)": "yfbzj",
    "内部应付款(万元)": "nbyfk",
    "其他应付款(万元)": "qtyfk",
    "预提费用(万元)": "ytfy",
    "预计流动负债(万元)": "yjldfz",
    "应付分保账款(万元)": "yffbzk",
    "保险合同准备金(万元)": "bxhtzbj",
    "代理买卖证券款(万元)": "dlmmzqk",
    "代理承销证券款(万元)": "dlcxzqk",
    "国际票证结算(万元)": "gjpzjs",
    "国内票证结算(万元)": "gnpzjs",
    "递延收益(万元)": "dysy",
    "应付短期债券(万元)": "yfdqzq",
    "一年内到期的非流动负债(万元)": "ynndqdfldfz",
    "其他流动负债(万元)": "qtldfz",
    "流动负债合计(万元)": "ldfzhj",
    "长期借款(万元)": "cqjq",
    "应付债券(万元)": "yfzq",
    "长期应付款(万元)": "cqyfk",
    "专项应付款(万元)": "zxyfk",
    "预计非流动负债(万元)": "yjfldfz",
    "长期递延收益(万元)": "cqdysy",
    "递延所得税负债(万元)": "dysdsfz",
    "其他非流动负债(万元)": "qtfldfz",
    "非流动负债合计(万元)": "fldfzhj",
    "负债合计(万元)": "fzhj",
    "实收资本(或股本)(万元)": "sszb",
    "资本公积(万元)": "zbgj",
    "减:库存股(万元)": "jkcg",
    "专项储备(万元)": "zxcb",
    "盈余公积(万元)": "yygj",
    "一般风险准备(万元)": "ybfxzb",
    "未确定的投资损失(万元)": "wqddtzss",
    "未分配利润(万元)": "wfplr",
    "拟分配现金股利(万元)": "nfpxjgl",
    "外币报表折算差额(万元)": "wbbbzsce",
    "归属于母公司股东权益合计(万元)": "gsymgsgdqyhj",
    "少数股东权益(万元)": "ssgdqy",
    "所有者权益(或股东权益)合计(万元)": "syzqy",
    "负债和所有者权益(或股东权益)总计(万元)": "fzhsyzqy"
}

XJLLB_CH2EN = {
"销售商品、提供劳务收到的现金(万元)": "xssptglwsddxj",
"客户存款和同业存放款项净增加额(万元)": "khckhtycfkxjzje",
"向中央银行借款净增加额(万元": "xzyyhjkjzje",
"向其他金融机构拆入资金净增加额(万元)": "xqtjrjgcrzjjzje",
"收到原保险合同保费取得的现金(万元)": "sdybxhtbfqddxj",
"收到再保险业务现金净额(万元)": "sdzbxywxjje",
"保户储金及投资款净增加额(万元)": "bhcjjtzkjzje",
"处置交易性金融资产净增加额(万元)": "czjyxjrzcjzje",
"收取利息、手续费及佣金的现金(万元)": "sqlxsxfjyjdxj",
"拆入资金净增加额(万元)": "crzjjzje",
"回购业务资金净增加额(万元)": "hgywzjjzje",
"收到的税费返还(万元)": "sddsffh",
"收到的其他与经营活动有关的现金(万元)": "sddqtyjyhdygdxj",
"经营活动现金流入小计(万元)": "jyhdxjlrxj",
"购买商品、接受劳务支付的现金(万元)": "gmspjslwzfdxj",
"客户贷款及垫款净增加额(万元)": "khdkjdkjzje",
"存放中央银行和同业款项净增加额(万元)": "cfzyyhhtykjzje",
"支付原保险合同赔付款项的现金(万元)": "zfybxhtpfkxdxj",
"支付利息、手续费及佣金的现金(万元)": "zflxsxfjyjdxj",
"支付保单红利的现金(万元)": "zfbdhldxj",
"支付给职工以及为职工支付的现金(万元)": "zfgzgyjwzgzfdxj",
"支付的各项税费(万元)": "zfdgxsf",
"支付的其他与经营活动有关的现金(万元)": "zfdqtyjyhdygdxj",
"经营活动现金流出小计(万元)": "jyhdxjlcxj",
"经营活动产生的现金流量净额(万元)": "jyhdcsdxjllje",
"收回投资所收到的现金(万元)": "shtzssddxj",
"取得投资收益所收到的现金(万元)": "qdtzsyssddxj",
"处置固定资产、无形资产和其他长期资产所收回的现金净额(万元)": "czgdzcwxzchqtcqzcsshdxjje",
"处置子公司及其他营业单位收到的现金净额(万元)": "czzgjjqtyydwsddxjje",
"收到的其他与投资活动有关的现金(万元)": "sddqtytzhdygdxj",
"减少质押和定期存款所收到的现金(万元)": "jszyhdqckssddxj",
"投资活动现金流入小计(万元)": "tzhdxjlrxj",
"购建固定资产、无形资产和其他长期资产所支付的现金(万元)": "gjgdzcwxzchqtcqzcszfdxj",
"投资所支付的现金(万元)": "tzszfdxj",
"质押贷款净增加额(万元)": "zydkjzje",
"取得子公司及其他营业单位支付的现金净额(万元)": "qdzgsjqtyydwzfdxjje",
"支付的其他与投资活动有关的现金(万元)": "zfdqtytzhdygdxj",
"增加质押和定期存款所支付的现金(万元)": "zjzyhdqckszfdxj",
"投资活动现金流出小计(万元)": "tzhdxjlcxj",
"投资活动产生的现金流量净额(万元)": "tzhdcsdxjllje",
"吸收投资收到的现金(万元)": "xstzsddxj",
"其中：子公司吸收少数股东投资收到的现金(万元)": "qzzgsxsssgdtzsddxj",
"取得借款收到的现金(万元)": "qdjksddxj",
"发行债券收到的现金(万元)": "fxzqsddxj",
"收到其他与筹资活动有关的现金(万元)": "sdqtyczhdygdxj",
"筹资活动现金流入小计(万元)": "czhdxjlrxj",
"偿还债务支付的现金(万元)": "chzwzfdxj",
"分配股利、利润或偿付利息所支付的现金(万元)": "fpgllrhcflxszfdxj",
"其中：子公司支付给少数股东的股利、利润(万元)": "qzzgszfgssgddgllr",
"支付其他与筹资活动有关的现金(万元)": "zfqtyczhdygdxj",
"筹资活动现金流出小计(万元)": "czhdxjlcxj",
"筹资活动产生的现金流量净额(万元)": "czhdcsdxjllje",
"汇率变动对现金及现金等价物的影响(万元)": "hlbddxjjxjdjwdyx",
"现金及现金等价物净增加额(万元)": "xjjxjdjwjzje",
"加:期初现金及现金等价物余额(万元)": "jqcxjjxjdjwye",
"期末现金及现金等价物余额(万元)": "qmxjjxjdjwye",
"净利润(万元)": "jlr",
"少数股东损益(万元)": "ssgdsy",
"未确认的投资损失(万元)": "wqrdtzss",
"资产减值准备(万元)": "zcjzzb",
"固定资产折旧、油气资产折耗、生产性物资折旧(万元)": "gdzczjyqzczhscxwzzj",
"无形资产摊销(万元)": "wxzctx",
"长期待摊费用摊销(万元)": "cqdtfytx",
"待摊费用的减少(万元)": "dtfydjs",
"预提费用的增加(万元)": "ytfydzj",
"处置固定资产、无形资产和其他长期资产的损失(万元)": "czgdzcwxzchqtcqzcdss",
"固定资产报废损失(万元)": "gdzcbfss",
"公允价值变动损失(万元)": "gyjjbdss",
"递延收益增加(减：减少)(万元)": "dysyzj",
"预计负债(万元)": "yjfz",
"财务费用(万元)": "cwfy",
"投资损失(万元)": "tzss",
"递延所得税资产减少(万元)": "dysdszcjs",
"递延所得税负债增加(万元)": "dysdsfzzj",
"存货的减少(万元)": "chdjs",
"经营性应收项目的减少(万元)": "jyxysxmdjs",
"经营性应付项目的增加(万元)": "jjxyfxmdzj",
"已完工尚未结算款的减少(减:增加)(万元)": "ywgswjskdjs",
"已结算尚未完工款的增加(减:减少)(万元)": "yjsswwgkdzj",
"其他(万元)": "qt",
"经营活动产生现金流量净额(万元)": "jyhdcsxjllje",
"债务转为资本(万元)": "zwzwzb",
"一年内到期的可转换公司债券(万元)": "ynndqdkzhgszq",
"融资租入固定资产(万元)": "rzzrgdzc",
"现金的期末余额(万元)": "xjdqmye",
"现金的期初余额(万元)": "xjdqcye",
"现金等价物的期末余额(万元)": "xjdjwdqmye",
"现金等价物的期初余额(万元)": "xjdjwdqcye",
"现金及现金等价物的净增加额(万元)": "xjjxjdjwdjzje",
}
